### ISSUE TITLE
Can you explain which codebase the pre-trained model was trained in?

### ISSUE THREAD

**Issue by Breeze-Zero** [zhangbingliang2019/DAPS#2]
I also have some pre-trained diffusion on my task, but DDPM-based training doesn't seem to replace your score based model directly, so I have the intention of retraining, and I would like to ask which codebase the model is trained on?

**Comment by zhangbingliang2019** [comment]
Regarding the diffusion model, we follow the [EDM](https://arxiv.org/abs/2206.00364) framework for formulation and [guided diffusion](https://github.com/openai/guided-diffusion) codebase for training. For other DDPM-based pre-trained diffusion model, one can use the wrapper [`model/precond.py/VPPrecond`](https://github.com/zhangbingliang2019/DAPS/blob/main/model/precond.py#L21). It supports DDPM with linear beta scheduler. For other beta scheduler, such as scaled linear, one have to modify accordingly to handle $\sigma^{-1}(t)$ correctly.

**Comment by Breeze-Zero** [comment]
@zhangbingliang2019 Hello, I have a plan to shorten the inference time of the model and would like to ask you about the feasibility. If I get a relatively clean solution from another IR model, can I use DAPS as x_start, in which case can I reduce the number of num_steps for annealing_scheduler while maintaining the effect? Of course, the sigma_max of annealing_scheduler seems to need to be adjusted as well.

**Comment by zhangbingliang2019** [comment]
Thanks for your question. Indeed, utilizing a relatively clean solution $x^\*$ from another model could potentially enhance performance. One possible way to incorporate this into the DAPS would be to replace x_start with $x^\* + \sigma_{\max} \epsilon$, where $\sigma_{\max}$ is adjusted based on your assessment of the quality of $x^\*$. This approach is also discussed in other Diffusion Purification literature. However, we have not yet fully explored or tested this idea within the context of DAPS. We are very interested in any results you might obtain from such an approach.
