### ISSUE TITLE
Question about reconstruction

### ISSUE THREAD

**Issue by TFNTF** [zhangbingliang2019/DAPS#4]
Could you please answer my following question:

What is the loss to constrain corresponding diffusion process to converge to a specific input image? For example (as shown in the phase retrieval results in your paper)

As far as I'm concerned, an unconditioned (text or other conditions) diffusion model can not recover a given image and it may add and remove noise randomly.

I'm looking forward to your reply!

**Comment by chuwd19** [comment]
The DAPS framework uses an unconditional diffusion process to model the prior distribution $p(x)$. As shown in Section 3.1 in our paper, DAPS follows a recursive sampling process that 1) samples $x_{0|y} \sim p(x_0| x_{t+dt}, y)$ and 2) samples $x_t \sim \mathcal N(x_{0|y}, \sigma_t^2 I) = p(x_t|y)$ where $y$ is some measurement of $x_0$ as defined in Equation (3). 

To answer your question, the constrain to converge to a specific input image is in step 1), which is done by a Langevin dynamics process as specified in Equation 7~9.
